# Generated by Django 4.2.10 on 2024-02-29 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="max_users",
        ),
        migrations.RemoveField(
            model_name="product",
            name="min_users",
        ),
    ]
