# Generated by Django 4.2.10 on 2024-02-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_product_alter_access_product_alter_group_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(max_length=512),
        ),
    ]
