# Generated by Django 4.2.10 on 2024-03-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="count_members",
            field=models.IntegerField(default=0),
        ),
    ]
